### ISSUE TITLE
Image not rendered

### ISSUE THREAD

**Issue by TangdizhiH** [MSzturc/obsidian-advanced-slides#52]
Problem: The image is not properly rendered in preview.

Reproduce: I don't know if anyone else has encountered the same problem. I just encountered it this time

below is the screen shot from my vault
![image](https://user-images.githubusercontent.com/45258158/154069460-42811fe0-4179-4084-8e05-b58456852eae.png)

Obsidian version: obsidian 0.13.23

Plugin version: the latest 1.6.0

**Comment by AxelRothe** [comment]
same problem here, it worked for a short time, then it stopped. I can't find an error code though

**Comment by AxelRothe** [comment]
Just found a solution for my version of this problem. I had to set "New link format" to "Absolut path in vault". It now loads the image correctly.

**Comment by MSzturc** [comment]
> I'm also having this problem, but only when I'm using markdown links `![]()` linking to either images inside or outside my vault. Images outside my vault don't render when the link has spaces or `%20`. Images inside my vault linked using markdown links never render even without `%20` in the link, but these same images would render when using wikilinks.

Can you provide me a sample? (Images & Markdown) Im not able to reproduce this behaviour

**Comment by MSzturc** [comment]
Closed, cant reproduce error

**Comment by winnubstj** [comment]
I am running into similar issue, seems to be related to image embedding and path lookup since html elements  do work:

Example WORKING MD (Image is in vault in same directory):
<img src="test.png">

Example Failing MD:
[[test.png]]

Get this error message in developer tools:

VM148:72947 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'path')
    at ObsidianUtils.findFile (eval at <anonymous> (app.js:1:1490278), <anonymous>:72947:58)
    at ImageProcessor.transformImageString (eval at <anonymous> (app.js:1:1490278), <anonymous>:72356:33)
    at eval (eval at <anonymous> (app.js:1:1490278), <anonymous>:72343:21)
    at Array.map (<anonymous>)
    at ImageProcessor.process (eval at <anonymous> (app.js:1:1490278), <anonymous>:72341:33)
    at ObsidianMarkdownPreprocessor.process (eval at <anonymous> (app.js:1:1490278), <anonymous>:72682:53)
    at RevealRenderer.render (eval at <anonymous> (app.js:1:1490278), <anonymous>:72762:46)
    at RevealRenderer.renderFile (eval at <anonymous> (app.js:1:1490278), <anonymous>:72747:33)
    at async eval (eval at <anonymous> (app.js:1:1490278), <anonymous>:72874:22)

Im on windows 10.
