### ISSUE TITLE
Slides not showing

### ISSUE THREAD

**Issue by marc0l92** [MSzturc/obsidian-advanced-slides#63]
I'm not able to display even a basic example of this plugin.

Here the logs in the console:
```
server started at http://localhost:3002

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toString')
    at RevealRenderer.renderFile (eval at <anonymous> (app.js:1:1444405), <anonymous>:72691:68)
    at eval (eval at <anonymous> (app.js:1:1444405), <anonymous>:72819:49)
    at Layer.handle [as handle_request] (eval at <anonymous> (app.js:1:1444405), <anonymous>:9564:9)
    at next (eval at <anonymous> (app.js:1:1444405), <anonymous>:9730:17)
    at Route.dispatch (eval at <anonymous> (app.js:1:1444405), <anonymous>:9712:7)
    at Layer.handle [as handle_request] (eval at <anonymous> (app.js:1:1444405), <anonymous>:9564:9)
    at eval (eval at <anonymous> (app.js:1:1444405), <anonymous>:9990:26)
    at Function.process_params (eval at <anonymous> (app.js:1:1444405), <anonymous>:10021:16)
    at next (eval at <anonymous> (app.js:1:1444405), <anonymous>:9985:15)
    at expressInit (eval at <anonymous> (app.js:1:1444405), <anonymous>:10239:9)

Uncaught (in promise) Error: ENOENT: no such file or directory, open '....censured...\.obsidian\plugins\obsidian-advanced-slides\template\reveal.html'

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:3002') does not match the recipient window's origin ('app://obsidian.md').
```

the content of the markdown file I'm trying to render is:
```md
---
created: 2022-04-08T17:42:49+02:00
updated: 2022-04-08T17:42:49+02:00
---
#### Hello from Cover Page

---

Greetings from second Slide

```

what I'm doing wrong? what is the missing file `obsidian-advanced-slides\template\reveal.html` ?

**Comment by marc0l92** [comment]
You are right, I have this issue only on the company laptop that uses vpn and firewall.

What is the url that you are trying to access to download the framework? Maybe I can request to whitelist it.

**Comment by MSzturc** [comment]
The files are hosted on github. Check the releases there is a zip file that gets downloaded on start.  As workaround you could download it manually and extract it info the plugin directory

**Comment by XMB-7** [comment]
> ...maybe something proxy / vpn related... Since the runtime environment isnt downloaded it couldnt render the slide properly...  As workaround you could download it manually and extract it info the plugin directory

Please mention this in readme. It really prevents me for using this awesome plugin for a long time. Thanks.

**Comment by jonasmmiguel** [comment]
In case someone else is behind a proxy and runs into a similar problem of preview not working because of incomplete installation:

1. copy this link (I took it from [here](https://github.com/MSzturc/obsidian-advanced-slides/blob/f2fc58abd0b05723c11c0bd7a8cd8293fcffd5f7/src/main.ts#L110), paste in your browser, replace `${version}` by [the current release version](https://github.com/MSzturc/obsidian-advanced-slides/releases): 
`https://github.com/MSzturc/obsidian-advanced-slides/releases/download/${version}/obsidian-advanced-slides.zip`
2. unzip it, copy its contents and replace the existing plugin directory contents in your vault (`<path-to-your-vault>/.obsidian/plugins/obsidian-advanced-slides/)`

Thanks @XMB-7 for pointing that out!
