### ISSUE TITLE
"Open in Browser" does not work reliable (Browser remains blank)

### ISSUE THREAD

**Issue by simonmeggle** [MSzturc/obsidian-advanced-slides#65]
See also forum post: https://forum.obsidian.md/t/advanced-slides-create-markdown-based-reveal-js-presentations-in-obsidian/28243/100

**Comment by scokobro** [comment]
I'm not sure if this is related as I don't really know enough about the internals of how AdvSlides works, however as it is related to image paths I thought I'd mention it here, in case it helps.

I have an image on of my slides - 

`![[/Excalidraw/Drawing 2022.excalidraw.png|600]]`

Note the slash at the start of the path - if this is present then the image appears as expected in the slide preview BUT I also get a warning telling me the image can't be found.

However, remove the preceding slash and:
1 - image disappears from the slide preview,
2 - no warning notifications about missing images, and
3 - I'm no html expert but the code for the `img` tag produced looks a little funky...
-> `<img src="/Excalidraw/Drawing 2022.excalidraw.svg|.png" alt="" style="width: 600px">`
with the `|` in the src path. 

Hope this helps.

**Comment by Liong1976** [comment]
The same here. I clicked "Open in Browser," it kept loading, and the screen was blank.

**Comment by lucasrodwell** [comment]
Same here, if there are embedded images in the file there is no preview at localhost:3000. The obsidian developers console (CTRL+SHIFT+i on linux mint) gives :

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'path')
    at ObsidianUtils.findFile (eval at <anonymous> (app.js:1:1), <anonymous>:72947:58)
    at ImageProcessor.transformImageString (eval at <anonymous> (app.js:1:1), <anonymous>:72356:33)
    at eval (eval at <anonymous> (app.js:1:1), <anonymous>:72343:21)
    at Array.map (<anonymous>)
    at ImageProcessor.process (eval at <anonymous> (app.js:1:1), <anonymous>:72341:33)
    at ObsidianMarkdownPreprocessor.process (eval at <anonymous> (app.js:1:1), <anonymous>:72682:53)
    at RevealRenderer.render (eval at <anonymous> (app.js:1:1), <anonymous>:72762:46)
    at RevealRenderer.renderFile (eval at <anonymous> (app.js:1:1), <anonymous>:72747:33)
    at async eval (eval at <anonymous> (app.js:1:1), <anonymous>:72874:22)

**Comment by MSzturc** [comment]
Thx for the bugreport, im still not sure why activeFile could be null at this point, since the slide itself is rendered from the activeFile, so it should be provided by obsidian. I've made the Image Lookup more robust, this issue should be fixed with 1.7.3

**Comment by airtonix** [comment]
does this feature still exist? I can't find how to open in browser
